### ISSUE TITLE
Add a "while" to conditional and looping commands

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [okamsn/loopy#10]
I notice that in the iteration and looping commands, there is no command for looping while an expression is true. The closes example I could find in the README is:

```elisp
(loopy (with  (j 0))
       ((do (cl-incf j))
        (when (> j 5)
          (return j)))) ; => 6
```

So it achieves an infinite loop but it does not check the "truthness" if any condition. 
I think such an inclusion would be useful.

**Comment by Luis-Henriquez-Perez** [comment]
I came up with this which seems to work.. A let is an anaphoric let from [this package](https://github.com/rolandwalker/anaphora) I used for my convenience. Of course we'd remove this dependency if we were to add this in.

I was thinking it might be better to have VAR be he first argument to be consistent with the other looping commands. Then we'd have it if there's only one argument assume that's the condition, but if there's two assume the first one is the variable and the second is the condition.

```elisp
(cl-defun lloopy-while-command-parser ((_ condition &optional var))
  "Loop while CONDITION is true optionally binding CONDITION to VAR."
  (let* ((pred (make-symbol "predicate"))
	 (explicit-vars (when var (list var pred)))
	 (main-body (alet `(setq ,pred ,condition)
		      (if var `(progn ,it (setq ,var ,pred)) it))))
    `((loopy--implicit-vars . (,pred ,condition))
      (loopy--pre-conditions . ,pred)
      (loopy--explicit-vars . ,explicit-vars)
      (loopy--main-body . ,main-body))))

(add-to-list 'loopy-custom-command-parsers
             (cons 'while #'lloopy-while-command-parser))

```

**Comment by okamsn** [comment]
The current challenge with having commands like `while` and `until` is that most variables are `nil` until being set in the loop body, meaning that things like the below don't work

``` elisp
(loopy ((list i '(1 2 3 10 7))
        ;; Assume this make the `while` loop check the condition:
        (while (< i 5)))) 
```

as `i` is only given the value `1` after checking the `while` loop's conditions.

I can think of two ways around this:

1. Always immediately set a variable to its first value.
    -  Use a `let*` instead of `let` for declaring variables. 
    - For destructuring, I think this would require removing the distinction between explicit and implicit variables. Maybe this distinction was never worthwhile.
    - Would need to decide how this would work with commands like `(when t (list i '(1 2))`.
2. Make some commands use a `cl-tagbody` to leave the loop without affecting the `cl-block`'s return value.  This is the closest thing I can think of to having something like Python's `break`
   - Wouldn't need to change the variable initializations. 
   - I think this is what the For package does. See the file [standard.lisp](https://github.com/Shinmera/for/blob/2e4fcfa0f9c1d2f4559c58cef20ccefa50ba180d/standard.lisp#L268).
   - Using a `tagbody` is probably inefficient.

`cl-loop` rearranges code so that assignments are done before checking conditions, but I think that would be harder with `loopy`, since `loopy` is more flexible about where assignments can occur.

``` elisp
(cl-loop for i in '(1 2 3 4)
         while (< i 3)
         collect i) ; => (1 2)

;; becomes
(cl-block nil
  (let* ((--cl-var-- '(1 2 3))
         (i nil)
         (--cl-var-- nil))
    (while (and (consp --cl-var--)
                (progn
                  (setq i (car --cl-var--))
                  (< i 3)))
      (push i --cl-var--)
      (setq --cl-var-- (cdr --cl-var--)))
    (nreverse --cl-var--)))

;; while this is different:
(cl-loop for i in '(1 2 3 4)
         collect i
         while (< i 3)) ; => (1 2 3)

;; and becomes
(cl-block nil
  (let* ((--cl-var-- '(1 2 3 4))
         (i nil)
         (--cl-var-- nil))
    (while (and (consp --cl-var--)
                (progn
                  (setq i (car --cl-var--))
                  (push i --cl-var--)
                  (< i 3)))
      (setq --cl-var-- (cdr --cl-var--)))
    (nreverse --cl-var--)))
```

**Comment by Luis-Henriquez-Perez** [comment]
I am leaning towards `1` because I can't think of a benefit to the distinction of explicit and implicit variables and because I also do not see a benefit between starting with all of the variables and nil versus starting all the variables at their initial value. Also, I favor more performant solutions.

> (when t (list i '(1 2))

For the sake of providing a full example.

```elisp
(loopy ((when t (list i '(1 2)))
	(collect i)))

;; => (1 2)

(let
    ((collect-implicit-3516 nil)
     (list-3515
      '(1 2))
     (i nil))
  (cl-block nil
    (while
	(consp list-3515)
      (when t
	(setq i
	      (car list-3515)))
      (setq collect-implicit-3516
	    (cons i collect-implicit-3516))
      (setq list-3515
	    (cdr list-3515)))
    (nreverse collect-implicit-3516)))
```
I don't understand completely. Do you mean that we'll end up missing the first value?

```elisp
;; fabricated macroexpansion of theoretical "immediate binding"
(let ((collect-implicit-3520 nil)
      (list-3519 (cdr '(1 2)))
      (i 1))
  (cl-block nil
    (while (consp list-3519)
      (when t
	(setq i (car list-3519)))
      (setq collect-implicit-3520
	    (cons i collect-implicit-3520))
      (setq list-3519
	    (cdr list-3519)))
    (nreverse collect-implicit-3520)))

;; => (2)
;; we end up missing 1

```

**Comment by Luis-Henriquez-Perez** [comment]
Upon more reflection, I changed my mind.

If tag bodies is the easier way and offers the least resistance to current design, then let's do that. Trying to redesign things to bind immediately might pose more problems and complications than it solves. And the performance we're striving for is still too nebulous. We haven't even benchmarked the two alternatives and compared them yet so we can't be completely sure which is more efficient (though of course we can guess) and how much more performant one is compared to the other and whether this difference is acceptable or not. Futhermore, as you mentioned the For package uses this and presumably this hasn't been a problem for the people who use it.

On a side note: Speaking of benchmarking if performance is a major goal of `loopy` maybe we should start benchmarking how it fares against `cl-loop` in several situations so that we get a good idea about how loopy is doing and where it could be improved, performance-wise at least.

**Comment by okamsn** [comment]
> ```emacs-lisp
> (loopy ((when t (list i '(1 2)))
> 	(collect i)))
> 
> ;; => (1 2)
> 
> (let
>     ((collect-implicit-3516 nil)
>      (list-3515
>       '(1 2))
>      (i nil))
>   (cl-block nil
>     (while
> 	(consp list-3515)
>       (when t
> 	(setq i
> 	      (car list-3515)))
>       (setq collect-implicit-3516
> 	    (cons i collect-implicit-3516))
>       (setq list-3515
> 	    (cdr list-3515)))
>     (nreverse collect-implicit-3516)))
> ```
> 
> I don't understand completely. Do you mean that we'll end up missing the first value?

I phrased this poorly. What I meant was that commands like `when` aren't aware of what they are wrapping. Sometimes, like in `(when COND (list i MY-LIST))`, they'll wrap assignments that need to be executed conditionally, but there is currently no distinction between variable assignments and other kinds of Lisp expressions. They are all just described as needing to be placed in the main section of the `while` loop's body.

I will implement the `tagbody` approach, and start making timing comparisons against `cl-loop`.

**Comment by okamsn** [comment]
Update: `while`, `until`, and `leave` commands have been added.

`leave` is the basic command which exits the loop without affecting the macros
return value.  `while` and `until` are convenience commands that function like
`(unless COND (leave))` and `(when COND (leave))`, respectively.

For convenience, `while` and `until` can take multiple arguments, each being a
condition to check.

**Comment by okamsn** [comment]
> On a side note: Speaking of benchmarking if performance is a major goal of `loopy` maybe we should start benchmarking how it fares against `cl-loop` in several situations so that we get a good idea about how loopy is doing and where it could be improved, performance-wise at least.

Comparisons to `cl-loop` are now available here: https://github.com/okamsn/loopy/wiki/Versus-%60cl-loop%60#speed-comparisons. `loopy` is (more or less) the same speed as `cl-loop`, since they are usually doing the same thing underneath.
