### ISSUE TITLE
concerns about efficiency of collect clause

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [okamsn/loopy#12]
I noticed from the macro expansion of the collect command, that `loopy` uses append to accumulate values into a list. I thought the most efficient way to do this is using `push` and `nreverse` (https://github.com/alphapapa/emacs-package-dev-handbook#collecting-items-into-a-list). Should this be changed?

**Comment by okamsn** [comment]
You are correct. I've changed `collect` so that it uses the `push`-`nreverse` idiom when a variable arugment isn't given, and appends a list when it isn't. This seems to be basically what `cl-loop` does, though `cl-loop` will use `nconc` depending on certain factors.

For reference for myself, see this section of `cl--parse-loop-clause`:

``` elisp
     ((memq word '(collect collecting))
      (let ((what (pop cl--loop-args))
	    (var (cl--loop-handle-accum nil 'nreverse)))
	(if (eq var cl--loop-accum-var)
	    (push `(progn (push ,what ,var) t) cl--loop-body)
	  (push `(progn
                   (setq ,var (nconc ,var (list ,what)))
                   t)
                cl--loop-body))))

     ((memq word '(nconc nconcing append appending))
      (let ((what (pop cl--loop-args))
	    (var (cl--loop-handle-accum nil 'nreverse)))
	(push `(progn
                 (setq ,var
                       ,(if (eq var cl--loop-accum-var)
                            `(nconc
                              (,(if (memq word '(nconc nconcing))
                                    #'nreverse #'reverse)
                               ,what)
                              ,var)
                          `(,(if (memq word '(nconc nconcing))
                                 #'nconc #'append)
                            ,var ,what)))
                 t)
              cl--loop-body)))
```

**Comment by Luis-Henriquez-Perez** [comment]
I'll close this since it looks like the collect clause is efficient (even more so than cl-loop's based on the wiki benchmark).
