### ISSUE TITLE
musings concerning possible additional clauses

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [okamsn/loopy#13]
There are general musings about inconveniences I've faced while looping.

1.
Often as I'm writing elisp, I want to iterate by more than one element at once. Something like this:

```elisp
(dolist (trio (-partition 3 '(1 2 3 4 5))
  ...)
```
The value of trio in the first iteration would be `(1 2 3)`.

It's not a huge deal to do this; it gets the job done. But it is sub-optimal. Partitioning the list, then looping through it when I could in theory collect sets of three elements during the first pass.
Maybe it would be nice to have a `partition` clause like `(partition element list n)`, where you traverse LIST N elements at a time, putting the (-take N list) in ELEMENT. Then again, maybe I'm the only one who feels this is a problem.

2.
Another candidate for a good possible clause is one that abstracts key value pairs such as alists, plists and hash tables. It would provide an element of the collection as a cons cell of the form (KEY . VALUE).

```elisp
(loopy ((key-val-clause (key . value) hash-or-alist-or-plist)
	(do-something-with key value)))
```

3.
Sometimes I want access to the rest of the list. My use case is inserting an item at a particular place in a plist. In the example below I try to use loopy to insert a keyword and value after a particular place in a plist. I use an undeclared variable REST (so this code doesn't work) that I would like to contain the rest of the list.

```elisp
(defun lleaf-insert-after (list place keyword value)
  "Insert KEYWORD and VALUE after PLACE."
  (loopy ((list element list)
	  ;; accumulate already-traversed elements into HEAD.
	  (collect head element)
	  (when (eq element place)
	    ;; when we find the PLACE, the keyword we want to insert after
	    ;; get it's value, (pop list), and put it in HEAD
	    (collect head (pop rest))
	    ;; Then put KEYWORD and VALUE into HEAD 
	    (append head (list keyword value))
	    ;; Return the plist with KEYWORD and VALUE inserted
	    (return (append head rest))))
	 (return list)))
```
This has to do with `(-drop N list)` and `(-take N list)`. 

I haven't thought of  a good way to deal with this yet.

**Comment by Luis-Henriquez-Perez** [comment]
While it is possible to create a `partition` clause as I mentioned in my first musing (number `1`). I think the `cons` looping clause solves this satisfactorily. It is possible to use `cddr` for a partition of two, `cdddr` for a partition of three and so on. This is also a good example of why destructuring is such a nice feature.

```elisp
(loopy ((cons (first second third) '(1 2 3 4 5 6 7 8 9) #'cdddr)
	(collect (+ first second third))))
;; => (6 15 24)
```

Additionally, I think I found a satisfactory way to do what I was looking to do in number `3` with a combination of destructuring and the `cons` clause. I think another good example of how powerful destructuring can be.

```elisp
(loopy (with (plist '(:a 1 :b 2 :c 3))
	     (place :c)
	     (key :x)
	     (value 5))
       ((cons (k v . tail) plist #'cddr)
	(append head (list k v))
	(when (eq k place)
	  (return (append head (list key value) tail))))
       (else-do (return plist)))

;; => (:a 1 :b 2 :c 3 :x 5)

(loopy (with (plist '(:a 1 :b 2 :c 3))
	     (place :y)
	     (key :x)
	     (value 5))
       ((cons (k v . tail) plist #'cddr)
	(append head (list k v))
	(when (eq k place)
	  (return (append head (list key value) tail))))
       (else-do (return plist)))

;; => (:a 1 :b 2 :c 3)
```

**Comment by Luis-Henriquez-Perez** [comment]
I think my ideas were bad in general or need more thought so I'll close this.

**Comment by okamsn** [comment]
> 2.  Another candidate for a good possible clause is one that abstracts key value
> pairs such as alists, plists and hash tables. It would provide an element of the
> collection as a cons cell of the form (KEY . VALUE).
>
> ```elisp
> (loopy ((key-val-clause (key . value) hash-or-alist-or-plist)
> 	(do-something-with key value)))
>
> ```

This was added as a `map` loop command, which uses the library `map.el`.  This
library generalizes working with alists, plists, hash tables, and vectors.  Once
consequence of this generalization is that the command finds all of the values
before the loop starts.

The most efficient way to work with tables would be to have a wrapper around the
function `maphash`, but I think that this is probably good enough for now.

``` emacs-lisp
       ;; NOTE: `pair' is not dotted.
       ;; => ((a 1) (b 2))
       (loopy (map pair '((a . 1) (b . 2)))
              (collect pair))

       ;; => ((a b) (1 2))
       (loopy (map (key value) '((a . 1) (b . 2)))
              (collect keys key)
              (collect values value))

       ;; => ((:a :b) (1 2))
       (loopy (map (key value) '(:a  1 :b 2))
              (collect keys key)
              (collect values value))

       ;; NOTE: For vectors, the keys are indices.
       ;; => ((0 1) (1 2))
       (loopy (map (key value) [1 2])
              (collect keys key)
              (collect values value))

       ;; => ((a b) (1 2))
       (let ((my-table (make-hash-table)))
         (puthash 'a 1 my-table)
         (puthash 'b 2 my-table)

         (loopy (map (key value) my-table)
                (collect keys key)
                (collect values value)))
```
