### ISSUE TITLE
idea: wiki for real-world examples

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [okamsn/loopy#15]
In the readme, you've already provided some real-life examples with loopy as well as contrived, didactic examples. I had been thinking that it might be useful to create a wiki with user examples of loops they've used. I could put some from my own config that I've used so solve problems. Or even interesting clause ideas could go there.

Even though I've suggested this idea, I'm not sure if it's a good idea or not, but I wanted to toss it in the air nevertheless.

**Comment by okamsn** [comment]
I think it's a good idea to move the current examples from the README to a wiki.  I was advised to not try distributing the examples with the library, and I don't think having incomplete examples (like it does now) is good style.

It is probably also good to move the comparisons with `cl-loop` to the wiki, and to separate the README from the Info documentation (though some information with be in both).

I've created a wiki page for custom commands, and another for examples. Please add anything you think would be useful.

**Comment by Luis-Henriquez-Perez** [comment]
A wiki exists so I will close this.
