### ISSUE TITLE
discussion: what it would take to support abitrarily nested clauses like iterate

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [okamsn/loopy#16]
I was reading the [source code](https://gitlab.common-lisp.net/iterate/iterate) of [iterate](https://common-lisp.net/project/iterate/#devel) the other day and I was pleasantly surprised at how short it is. I thought maybe we overestimated the difficulty in implementing this. I wanted to create this issue just as a place to discuss what it would take to implement this for loopy. The goal would be to get more concrete idea of what this would entail without making any commitments.

One easy step I could do is just start porting some of iterate's helper function to elisp. For many of them this is trivial. And then, try to understand how it works.

**Comment by Luis-Henriquez-Perez** [comment]
So in regards to this issue, I am considering starting a repo with the purpose of porting iterate to elisp. Then I could start porting iterate little by little. And from there we could then see about merging the two projects--or at least as much as we need to to support arbitrarily nested clauses. What do you think of this idea?

**Comment by okamsn** [comment]
That sounds good to me. There is probably more community interest in an Elisp `iterate` library than having another `cl-loop` like `loopy`.

**Comment by Luis-Henriquez-Perez** [comment]
I see that you've been working on a `loopy-iter` macro. Very exiting!

I noticed in your description you write that

> to be able to clearly distinguish between loop commands
>   (like =list=) and functions/macros (like ~list~).  This is done by using the
>   keywords =for=, =accum=, or =exit= in front of loop commands, as those words
>   do not match any built-in function in Emacs and are similar to what is used by
>   other packages.

I wonder if we can use the keywods (for, accum, and exist) optionally to distinguish keywords. It seems a bit much to use them all the time, particularly when many of the loopy clauses already have names that don't match built-in functions in Emacs. Using aliases (which I also see has been committed) further allows the user to ensure that there are no clashes.

Perhaps, this is a `flag` potential. A `(flag lax-naming)` could let the user, choose not to have to put these keywords in nested clauses--at their own risk of course they have to make sure to use the keywords that have no emacs conflicts.

**Comment by okamsn** [comment]
> I noticed in your description you write that
> 
> > to be able to clearly distinguish between loop commands
> > (like =list=) and functions/macros (like ~list~).  This is done by using the
> > keywords =for=, =accum=, or =exit= in front of loop commands, as those words
> > do not match any built-in function in Emacs and are similar to what is used by
> > other packages.
> 
> I wonder if we can use the keywods (for, accum, and exist) optionally to distinguish keywords. It seems a bit much to use them all the time, particularly when many of the loopy clauses already have names that don't match built-in functions in Emacs. Using aliases (which I also see has been committed) further allows the user to ensure that there are no clashes.
> 
> Perhaps, this is a `flag` potential. A `(flag lax-naming)` could let the user, choose not to have to put these keywords in nested clauses--at their own risk of course they have to make sure to use the keywords that have no emacs conflicts.

This flag has been added.

**Comment by Luis-Henriquez-Perez** [comment]
This is being handled by #47 so I will close this.
