### ISSUE TITLE
idea: potential alias for `list` clause `for`

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [okamsn/loopy#19]
Perhaps it would be nice provide an alias the `list` clause as `for`. `for` would look more like what's used in the other looping constructs which are similar to loopy including in `cl-loop`. Also it arguably is more intuitive than `list`.

**Comment by okamsn** [comment]
`cl-loop` uses word like "`in`" and "`across`" after "`for`" to distinguish between working on lists and working on arrays. The Iterate package in Common Lisp works similarly.

``` elisp
;; `cl-loop':
(cl-loop for x in '(1 2 3 4 5 6) collect (* x x))
(cl-loop for x on '(1 2 3 4) collect x)
(cl-loop for x across "aeiou"
         do (use-vowel (char-to-string x)))

;;; `iter':
for var in list &optional by step-function
for var on list &optional by step-function
for var in-vector vector &sequence

;;; `loopy'
(list x '(1 2 3 4 5 6))
(cons x '(1 2 3 4))
(array x "aeiou")
```

In `loopy`, I chose to use words like "`list`" and "`array`" to try to be more descriptive about what is being done. I occasionally have to look up the correct keyword in `cl-loop'.

Do you think that `for` is understood to be clearly about lists? 

Are there other names of commands that you think could be improved or aliases added?

**Comment by Luis-Henriquez-Perez** [comment]
> Do you think that for is understood to be clearly about lists?

No, probably not. My suggestion is probably not a good idea.

Are there other names of commands that you think could be improved or aliases added?

Not that I can think of right now, but I'll make an issue if I do.

**Comment by Luis-Henriquez-Perez** [comment]
Maybe do should be aliased as `progn` actually. What do you think?

**Comment by Luis-Henriquez-Perez** [comment]
Also, perhaps an alias of `with` could be `let`.

**Comment by okamsn** [comment]
> Maybe do should be aliased as `progn` actually. What do you think?

It was, but I removed it when I added the `group` command, which acts like a `progn` for the loop commands, grouping them together. I'm indecisive about this.

> Actually does `do` interfere with `cl-do`?

Not from what I have seen.  Please let me know if you experience otherwise.

> Also, perhaps an alias of `with` could be `let`.

If it helps, `let*` is already an alias of `with`, as variables initialized using `with` are created with a`let*`-form. I'm not against adding `let` too, but `let*` is more accurate.

**Comment by Luis-Henriquez-Perez** [comment]
> If it helps, let* is already an alias of with, as variables initialized using with are created with alet*-form. I'm not against adding let too, but let* is more accurate.

Good point. Let's keep that as it is then.

> It was, but I removed it when I added the group command, which acts like a progn for the loop commands, grouping them together. I'm indecisive about this.

What was the reason why you decided to remove it?

**Comment by okamsn** [comment]
> > It was, but I removed it when I added the group command, which acts like a progn for the loop commands, grouping them together. I'm indecisive about this.
> 
> What was the reason why you decided to remove it?

Both the `group` and `do` commands eventually turn into a `progn` form, and so both can be accurately named by a `progn` alias. `do` is a `progn` for Lisp expressions, while `group` is a `progn` for loop commands.

Since `progn` applies equally well to both, I decided to remove it to avoid confusion.

**Comment by Luis-Henriquez-Perez** [comment]
>Both the group and do commands eventually turn into a progn form, and so both can be accurately named by a progn alias. do is a progn for Lisp expressions, while group is a progn for loop commands.

>Since progn applies equally well to both, I decided to remove it to avoid confusion.

Ah, ok. In that case, let's leave things as they are.

Also, should we add an alias of `initially-do` for `before-do`? The reason would be to provide a parallel to `cl-loop`.

**Comment by Luis-Henriquez-Perez** [comment]
I think we can close this. Though, I think the `do`/`progn` thing might still be pertenent but I think #44 handles this. Reopen if you disagree.
