### ISSUE TITLE
unexpected behavior--extra `collect-implicit`

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [okamsn/loopy#21]
I am writing a general macro to bind keys for myself (maybe I will create a package for it). In it I wrote this function.

```elisp
(defun bind:parse-clause (parsers clause)
  "Return list of tokens from parsing CLAUSE with PARSERS."
  (loopy (without clause)
	 ((while clause)
	  (expr elt (pop clause))
	  (cond ((bind:is-valid-token-p elt)
		 (collect elt))
		((listp elt)
		 (collect (bind:parse-clause parsers elt)))
		(t
		 (expr (elt . clause) (bind:read-token parsers (cons elt clause)))
		 (collect elt))))))
```

I thought this would work like this and as far as I can tell it should. Right?

```elisp
(defun bind:parse-clause (parsers clause)
  "Return list of tokens from parsing CLAUSE with PARSERS."
  (let (elt parsed)
    (while clause
      (setq elt (pop clause))
      (cond ((bind:is-valid-token-p elt)
	     (push elt parsed))
	    ((listp elt)
	     (push (bind:parse-clause parsers elt) parsed))
	    (t
	     (-setq (elt . clause) (bind:read-token parsers (cons elt clause)))
	     (push elt parsed))))
    (reverse parsed)))
```
Weird thing is I get completely different results for the two.

It looks like it's making extra lists in the macroexpansion

```elisp
(let
    ((elt nil))
  (let*
      ((collect-implicit-149406 nil)
       (collect-implicit-149404 nil)
       (collect-implicit-149403 nil))
    (cl-block nil
      (cl-tagbody
       (while t
	 (if clause nil
	   (go loopy--non-returning-exit-tag))
	 (setq elt
	       (pop clause))
	 (cond
	  ((bind:is-valid-token-p elt)
	   (setq collect-implicit-149403
		 (cons elt collect-implicit-149403)))
	  ((listp elt)
	   (setq collect-implicit-149404
		 (cons
		  (bind:parse-clause parsers elt)
		  collect-implicit-149404)))
	  (t
	   (setq clause
		 (bind:read-token parsers
				  (cons elt clause)))
	   (setq elt
		 (pop clause))
	   (setq clause clause)
	   (setq collect-implicit-149406
		 (cons elt collect-implicit-149406)))))
       loopy--non-returning-exit-tag)
      (list
       (nreverse collect-implicit-149406)
       (nreverse collect-implicit-149404)
       (nreverse collect-implicit-149403)))))
```

My version of loopy is at commit:

1cf221e * master origin/master Add test case to make sure repeated evaluation doesn’t raise errors.

**Comment by okamsn** [comment]
Things are currently set up so that accumulation commands will each use their own accumulation variable when no variable is named. This was more convenient for what I was doing at the time.

I try to explain this [here](https://github.com/okamsn/loopy/blob/master/doc/loopy.org#accumulation-commands):
> Like `cl-loop`, you do not need to supply a variable name to accumulation commands. With only one argument, they accumulate values into a generated variable and use that variable as an implicit return value. Unlike `cl-loop`, this generation means that if you want accumulation commands to act on the same variable, you must supply the same `VAR` as the first argument to each command.

The `push-into` command is a way to work around this:

```elisp
(defun bind:parse-clause (parsers clause)
  "Return list of tokens from parsing CLAUSE with PARSERS."
  (loopy (without clause)
	 ((while clause)
	  (expr elt (pop clause))
	  (cond ((bind:is-valid-token-p elt)
		 (push-into tokens elt))
		((listp elt)
		 (push-into tokens (bind:parse-clause parsers elt)))
		(t
		 (expr (elt . clause) (bind:read-token parsers (cons elt clause)))
		 (push-into tokens elt))))
         (return (nreverse tokens))))
```

It will expand to the expected code:

```elisp
(let ((tokens nil)
      (elt nil))
  (cl-block nil
    (cl-tagbody
     (while t
       (if clause nil (go loopy--non-returning-exit-tag))
       (setq elt (pop clause))
       (cond
        ((bind:is-valid-token-p elt)
         (push elt tokens))
        ((listp elt)
         (push
          (bind:parse-clause parsers elt)
          tokens))
        (t
         (setq clause (bind:read-token parsers (cons elt clause)))
         (setq elt (pop clause))
         (push elt tokens))))
     loopy--non-returning-exit-tag)
    tokens)
  (nreverse tokens))
```

You can also use `collect` with the same variable, but it is less efficient if you don't need to access said variable.

Do you think that it would be better if all accumulation commands without named variables would use the same generated variable?

**Comment by Luis-Henriquez-Perez** [comment]
> Things are currently set up so that accumulation commands will each use their own accumulation variable when no variable is named.

Oh.

> Do you think that it would be better if all accumulation commands without named variables would use the same generated variable?

For me at least, that is more intuitive. I assumed that collect would add into the same variable unless I specified otherwise (via a named collect). If I needed more lists, then I would rather name each of them than handle them indirectly with unnamed collects. Indeed, we should probably not encourage doing such a thing because I think it would make code less readable.

**Comment by okamsn** [comment]
I've updated `loopy` to work more like `cl-loop` in this regard. Collections that don't specify `VAR` will now all accumulate into the same variable, by default named `loopy-result` (see #23).

The old behavior, which can be more efficient in a small number of cases, by be triggered by a new `split` flag, which will split the accumulations into separate variables.

Does these changes work as you expect?

``` elisp
;; => (1 2 3 4 5)
(loopy (loop (list i '(1 2 3 4 5))
             (if (cl-oddp i)
                 (collect i)
               (collect i)))
       ;; For un-named loops, the variable is `loopy-result'.
       (finally-return loopy-result))

;; => ((1 3 5) (2 4))
(loopy (flag split)
       (loop (list i '(1 2 3 4 5))
             (if (cl-oddp i)
                 (collect i)
               (collect i))))

;; Both of these example give the same result, but the latter
;; can expand into more efficient code.
;; There is also the `push-into' commands, avoids this problem.

;; => ((1 4) (2 5) (3 6))
(loopy (loop (list elem '((1 2 3) (4 5 6)))
             (collect (i j k) elem)))

;; => ((1 4) (2 5) (3 6))
(loopy (flag split) ; Don't accumulate into same implicit variable.
       (loop (list (i j k) '((1 2 3) (4 5 6)))
             (collect i)
             (collect j)
             (collect k)))
```

**Comment by Luis-Henriquez-Perez** [comment]
Yes, this works as I expected.

**Comment by okamsn** [comment]
Closing this, since the behavior should be stable now.  Please re-open if you
have any problems.
