### ISSUE TITLE
request: more convenient and scalable syntax for nesting loops

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [okamsn/loopy#24]
I'd like to devise a better syntax for nested loops as it stands, I would not be very fond writing double nested loops (or even loops of a greater nest) for loopy. The syntax is a lot and it does not scale well for N-nested loops. I'd like a way to specify the lists in a "flat" way as opposed to nesting forms.

```elisp
(loopy outer-loop
       ((list inner-list '((1 2 3) (1 bad-val? 1) (4 5 6)))
        (do (loopy ((list i inner-list)
                    (when (eq i 'bad-val?)
                      (return-from outer-loop 'bad-val?)))))))
```

Here's a clearer picture of what I mean. Of course their is `-table-flat` from dash, but the downside is it is not as performant as looping. I bet we can use macros to get a flat, scalable syntax that is also performant (ie. expands to while loop/dolist).

```elisp
;; Does not scale well for N nests because you have to keep nesting forms.
(dolist (i '(1 2 3 ))
  (dolist (j '(4 5 6 7))
    (ignore 'this)))

;; Stays the same for N nests. But the problem is it is not as efficient as the former.
(loopy ((list (i j) (-table-flat #'list '(1 2 3) '(4 5 6 7)))
	(do (ignore 'this))))
```

**Comment by okamsn** [comment]
With #73 and #76 merged, I think that this can be closed. 

The new multi-sequence support does create the distributed sequence ahead of time, so it is still not as efficient as using the multiple `dolist`s, but that would be hard to do while supporting the keyword arguments to each of the affected iteration commands.

If needed, one can instead use the `wrap` special macro argument to be sure that one is using `dolist`.

I think these options satisfy the desired result of this request, if not the exact behavior. Please re-open this issue if you disagree.
