### ISSUE TITLE
idea: convenient and "flat" wrapping of forms around loopy

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [okamsn/loopy#27]
I think it's safe to say one of loopy's goals is to to write everything that concerns a loop within the loopy macro. That is why clauses like `with` and `before-do` exist even though they could be done outside loopy. With this in mind, i was thinking maybe the `when` clause could work outside of a loopy loop.

```elisp
(loopy (with (my-list '((1 2 3))))
       (when (some-condition))
       ((list i '(1 2 3 4))
	(collect (+ i i))))

;; Would be equivalent to below.

(when (some-condition)
  (loopy (with (my-list '((1 2 3))))
	 ((list i '(1 2 3 4))
	  (collect (+ i i)))))
```

In fact we can go even further and support arbitrary wrappers. For instance, typically in emacs you want to wrap a loop with `save-excursion` or `save-match-data` or `save-restrictions`.

```elisp
(loopy (wrap ((when (= 1 2)) (save-excursion) (save-match-data)))
       ((while (re-search-forward "someregexp" nil t nil)
	  (collect (match-data)))))
;; =>

(when (= 1 2)
  (save-excursion
    (save-match-data
      (loopy
       ((while (re-search-forward "someregexp" nil t nil)
	  (collect (match-data))))))))
```

**Comment by okamsn** [comment]
> I think it's safe to say one of loopy's goals is to to write everything that concerns a loop within the loopy macro. That is why clauses like `with` and `before-do` exist even though they could be done outside loopy. 

It's more to be consistent with `cl-loop`, which has similar clauses. `with` can be used to control the initial values of variables named in the loop, but that's not as important now that we have a `without` macro argument.

> With this in mind, i was thinking maybe the `when` clause could work outside of a loopy loop.
> 
> ```emacs-lisp
> (loopy (with (my-list '((1 2 3))))
>        (when (some-condition))
>        ((list i '(1 2 3 4))
> 	(collect (+ i i))))
> 
> ;; Would be equivalent to below.
> 
> (when (some-condition)
>   (loopy (with (my-list '((1 2 3))))
> 	 ((list i '(1 2 3 4))
> 	  (collect (+ i i)))))
> ```
> 
> In fact we can go even further and support arbitrary wrappers. For instance, typically in emacs you want to wrap a loop with `save-excursion` or `save-match-data` or `save-restrictions`.
> 
> ```emacs-lisp
> (loopy (wrap ((when (= 1 2)) (save-excursion) (save-match-data)))
>        ((while (re-search-forward "someregexp" nil t nil)
> 	  (collect (match-data)))))
> ;; =>
> 
> (when (= 1 2)
>   (save-excursion
>     (save-match-data
>       (loopy
>        ((while (re-search-forward "someregexp" nil t nil)
> 	  (collect (match-data))))))))
> ```

You would probably need to add a new instruction for something like this.

**Comment by okamsn** [comment]
The `wrap` special macro argument was added in #76.

Similar to `thread-last`, you can do either of the following.

``` elisp
(loopy (wrap (when (= 1 2)) (save-excursion) (save-match-data))
       (while (re-search-forward "someregexp" nil t nil))
       (collect (match-data)))

(loopy (wrap (when (= 1 2)) save-excursion save-match-data)
       (while (re-search-forward "someregexp" nil t nil))
       (collect (match-data)))
```

which both currently expand to something like

``` elisp
(let* ((loopy-result nil))
  (let ((loopy--accumulations-updated nil))
    (let ((loopy-first-iteration t))
      (cl-block nil
        (cl-tagbody
         (when (= 1 2)
           (save-excursion
             (save-match-data
               (while t
                 (if (re-search-forward "someregexp" nil t nil)
                     nil
                   (go loopy--non-returning-exit-tag))
                 (setq loopy-result (cons (match-data) loopy-result))
                 (setq loopy-first-iteration nil))
               (setq loopy-result (cl-coerce (nreverse loopy-result) 'list))
               (setq loopy--accumulations-updated t))))
         loopy--non-returning-exit-tag
         (if loopy--accumulations-updated
             nil
           (setq loopy-result (cl-coerce (nreverse loopy-result) 'list))))
        loopy-result))))
```
