### ISSUE TITLE
let multiple uses of `loop` command trigger different loops

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [okamsn/loopy#32]
As it stands these things seem equivalent:

```elisp
(loopy (loop (list a '(1 2 3 4))
	     (collect a))
       (loop (list b '(5 6 7))
	     (collect b)))

;=> (1 5 2 6 3 7)

(loopy (loop (list a '(1 2 3 4))
	     (list b '(5 6 7))
	     (collect a)
	     (collect b)))

;=> (1 5 2 6 3 7)
```
But maybe they shouldn't be. I understand that the latter form returns what it does. But I expected two different loops in the former. So two consecutive while loops. Perhaps this could be optional behaviour designated by a flag.

In this case, the loopy loop would return this.

```elisp
(loopy (loop (list a '(1 2 3 4))
	     (collect a))
       (loop (list b '(5 6 7))
	     (collect b)))

;=> (1 2 3 4 5 6 7)
````

**Comment by okamsn** [comment]
> ```emacs-lisp
> ;=> (1 5 2 6 3 7)
> (loopy (loop (list a '(1 2 3 4))
> 	     (collect a))
>        (loop (list b '(5 6 7))
> 	     (collect b)))
> ```

The macro just tries to interpret each macro argument as it reads them (except for things like `with` or `flag`, which need to be interpreted first), so this  is equivalent to the following.

``` emacs-lisp
(loopy (loop (list a '(1 2 3 4))
	     (collect a)
             (list b '(5 6 7))
	     (collect b))
```

Please see #33 for changes I am considering regarding this.

**Comment by okamsn** [comment]
UPDATE: The `loop` command now triggers different loops.

The `sub-loop` (with alias `loop`) loop command can be used to create sub-loops.
The super-loop is still created, though.  It can be exited with a simple
`(repeat 1)`, so I'm not sure whether it is worth adding a flag to disable the
over-loop.

``` emacs-lisp
;; => (1 2 3 4 5 6 7)
(loopy (repeat 1)
       (loop (list a '(1 2 3 4))
	         (collect a))
       (loop (list b '(5 6 7))
             (collect b)))

;; Expands to:
(let ((loopy-result nil))
  (let* ((repeat-limit-245 0))
    (cl-block nil
      (while (< repeat-limit-245 1)
        (let* ((list-247 '(1 2 3 4))
               (a nil))
          (cl-block sub-loop-246
            (while (consp list-247)
              (setq a (car list-247))
              (setq loopy-result (cons a loopy-result))
              (setq list-247 (cdr list-247)))
            nil))
        (let* ((list-249 '(5 6 7))
               (b nil))
          (cl-block sub-loop-248
            (while (consp list-249)
              (setq b (car list-249))
              (setq loopy-result (cons b loopy-result))
              (setq list-249 (cdr list-249)))
            nil))
        (setq repeat-limit-245 (1+ repeat-limit-245)))
      (setq loopy-result (nreverse loopy-result))
      loopy-result)))

```
