### ISSUE TITLE
feature: allow destructuring in list/seq clause

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [okamsn/loopy#4]
The idea is to allow destructuring in the seq/list clause. I haven't explored it thoroughly, but seems cool at a glance.

```elisp
(loopy ((seq (a . b) '((1 . 2) (3 . 4)))
        (collect keys a)
	(collect values b))
       (return (list keys values)))
;; => '((1 3) (2 4))

```

**Comment by okamsn** [comment]
I plan to add destructuring after trying to reduce code duplication. I'm going to first try to break down the command parsing into smaller functions, then I'll come back to improve the commands.

**Comment by Luis-Henriquez-Perez** [comment]
Sounds good. If you want to tag some issues as `#good-first-issues`, I might be able to help.

**Comment by okamsn** [comment]
I've added destructuring for the `list`, `array`, and `seq` commands.  I've
tried to add destructuring for the `list-ref`, `array-ref`, and `seq-ref`
commands, but the `setf`-able destructuring probably isn't the most efficient
yet.

Destructuring only works on lists so far, but I will try to add it for arrays
later.  I'm also considering just enabling it for most/all of the commands that
assign to variables.

The tests I wrote say that it is working, but does it work for you?

**Comment by okamsn** [comment]
I've added array destructuring and allowed destructuring for all commands that assign a variable.

**Comment by Luis-Henriquez-Perez** [comment]
Sorry for the late response.

The destructuring features you've added look _really_ amazing. I particularly like how they work with accumulation commands as you described in the readme.

I didn't really have a methodology behind my testing, I just wanted to see if I could break it by doing more complex destructurings. Based on the tests you added in `list-destructuring` I expected these to work.

```elisp
;; One of your list destructuring tests.
(loopy ((list (a . b) '((1 . 2) (3 . 4) (5 . 6))))
       (finally-return a b))

;; Some examples I tried that I thought should work based on your list destructuring tests.

;; expected (5 5 6), but I get an error.
(loopy ((list (a (b c)) '((1 (1 2)) (3 (3 4)) (5 (5 6)))))
       (finally-return (list a b c)))
       
;; should return (5 5 6), but I get an error.
(loopy ((list (a . [b c]) '((1 . [1 2]) (3 . [3 4]) (5 . [5 6]))))
       (finally-return (list a b c)))
```

Specifically, the errors said `(wrong-type-argument symbolp (b c))` and `(gv-invalid-place [b c])` respectively.

On a side note, I notice that you mention briefly the issue of there not being an implicit return value in loopy. I don't know, I think this has benefits and drawbacks. I wonder whether there isn't a way to intelligently determine when to implicitly return and when to not. In the absence of a return statement, perhaps it can return what you'd expect from an equivalent `cl-loop` form. I'm not sure if there are any ambiguous cases we'd have to watch out for.

**Comment by okamsn** [comment]
Thank you for testing it.

> ``` emacs-lisp
> ;; Some examples I tried that I thought should work based on your list destructuring tests.
>
> ;; expected (5 5 6), but I get an error.
> (loopy ((list (a (b c)) '((1 (1 2)) (3 (3 4)) (5 (5 6)))))
>        (finally-return (list a b c)))
>
> ;; should return (5 5 6), but I get an error.
> (loopy ((list (a . [b c]) '((1 . [1 2]) (3 . [3 4]) (5 . [5 6]))))
>        (finally-return (list a b c)))
> ```

I hadn't thought about recursive destructuring.  I will work on this.

Regarding implicit return values, I agree that it would be good to add that
feature.  Ideally, one shouldn't have to type much more than what they would for
Common Lisp's `iterate` or `for` macros.  I will create a new issue for this.

**Comment by okamsn** [comment]
Recursive destructuring should work now, and implicit returns have been implemented for accumulation commands.

**Comment by Luis-Henriquez-Perez** [comment]
I have begun using loopy more in my configuration.
While doing so, I found behavior which was unexpected to me.

I had been working on getting the keywords in the variable `leaf-keywords`.

For simplicity, I'll deal with just two of its elements. The problem is reproduced with just two.

```elisp
(-take 2 leaf-normalize) ;; =>
'(((memq leaf--key '(:require)) 'some-consequent)
  ((memq leaf--key '(:load-path :load-path* :commands :after :defvar)) 'some-consequent))
```

I wrote a loop to get the (cl-third (cl-first element)) for each element. In this two element list. 
I would expect `'((:require) (:load-path :load-path* :commands :after :defvar))`. But instead I get an error.

```elisp
(loopy ((list ((_ _ c) _) (-take 2 leaf-normalize))
	(collect c)))
;; =>
;; Debugger entered--Lisp error: (wrong-type-argument listp leaf--key)
;;  car(leaf--key)
;;  (setq _ (car _))
```

Just to make sure my destructuring is not off I try it in using dash's --each.

```elisp
(let (result)
  (--each (-take 2 leaf-normalize)
    (-let ((((_ _ c) _) it))
      (push c result)))
  (nreverse result))

('(:require) '(:load-path :load-path* :commands :after :defvar))
```

**Comment by okamsn** [comment]
Thank you for continuing to test this package. 

This problem happens because `loop` is setting and popping the variable `_` in a way that doesn't work in this case. I'm going to explicitly add `_` as a way to request a temporary variable (and maybe avoid some assignments?). For now, the destructuring needs unique variable names.

For the record, what you wrote currently expands to

``` elisp
(let ((g445 nil)
      (g444 (-take 2 leaf-normalize))
      (c nil)
      (_ nil))
  (cl-block nil
    (while (consp g444)
      (setq _ (car g444))
      (setq c (pop _))
      (setq _ (pop c))
      (setq _ (pop c))
      (setq c (car c))
      (setq _ (car _))
      (setq g445 (append g445 (list c)))
      (setq g444 (cdr g444)))
    g445))
```
but with separate variable names the assignments should work correctly:

``` elisp
;; => ('(:require) '(:load-path :load-path* :commands :after :defvar))
(loopy ((list ((_a _b c) _d) (-take 2 leaf-normalize))
	(collect c)))

(let ((g447 nil)
      (g446 (-take 2 leaf-normalize))
      (_b nil)
      (_a nil)
      (c nil)
      (_d nil))
  (cl-block nil
    (while (consp g446)
      (setq _d (car g446))
      (setq c (pop _d))
      (setq _a (pop c))
      (setq _b (pop c))
      (setq c (car c))
      (setq _d (car _d))
      (setq g447 (append g447 (list c)))
      (setq g446 (cdr g446)))
    g447))
```

Does it work for you if you use unique variable names?

**Comment by okamsn** [comment]
For comparison and reference, this is how Dash does it:

``` elisp
(let (result)
  (--each (-take 2 leaf-normalize)
    (-let ((((_ _ c) _) it))
      (push c result)))
  (nreverse result))

;; Expands to:
(let (result)
  (let ((list (-take 2 leaf-normalize))
        (it-index 0))
    (while list
      (let ((it (car list)))
        (let ((input0 it))
          (let* ((--dash-source-716-- input0)
                 (c (nth 2 (car-safe
                            (prog1 --dash-source-716--
                              (setq --dash-source-716--
                                    (cdr --dash-source-716--))))))
                 (_ (car --dash-source-716--)))
            (setq result (cons c result)))))
      (setq it-index (1+ it-index))
      (setq list (cdr list))))
  (nreverse result))
```

**Comment by Luis-Henriquez-Perez** [comment]
> Thank you for continuing to test this package.

I'll be using loopy for any complex loop I write, so you can bet I'll keep on testing it.

> Does it work for you if you use unique variable names?

Yes, in that case it works for me. Thank you for the reference.

**Comment by okamsn** [comment]
Underscores as names should now work.

``` emacs-lisp
;; => ('(:require) '(:load-path :load-path* :commands :after :defvar))
(loopy ((list ((_ _ c) _) (-take 2 leaf-normalize))
	(collect c)))

;; Exapnds to:
(let ((collect-implicit-500 nil)
      (list-496 (-take 2 leaf-normalize))
      (discarded-value-499 nil)
      (discarded-value-498 nil)
      (c nil)
      (discarded-value-497 nil))
  (cl-block nil
    (while (consp list-496)
      (setq discarded-value-497 (car list-496))
      (setq c (pop discarded-value-497))
      (setq discarded-value-498 (pop c))
      (setq discarded-value-499 (pop c))
      (setq c (car c))
      (setq discarded-value-497 (car discarded-value-497))
      (setq collect-implicit-500 (cons c collect-implicit-500))
      (setq list-496 (cdr list-496)))
    (nreverse collect-implicit-500)))
```

**Comment by Luis-Henriquez-Perez** [comment]
I'll play with it on my end and close this after a few days if I can't break it.

**Comment by okamsn** [comment]
I haven't noticed any problems with destructuring for a while, so I am closing
this issue. Please re-open if you find that it still doesn't work.
