### ISSUE TITLE
counterpart to `append`: `prepend`

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [okamsn/loopy#40]
While writing `loopy` loops sometimes I want to `append` to the beginning of the list instead of at the end. This might be generally useful enough to include in loopy itself.

**Comment by okamsn** [comment]
I've added a `prepend` command that uses the function `append` for explicit accumulation
results and the function `nconc` for implicit accumulation results.  Please let me know
whether this works for you.

**Comment by Luis-Henriquez-Perez** [comment]
It seems to well. Should I close this?

**Comment by okamsn** [comment]
> It seems to well. Should I close this?

If you are satisfied with the behavior, then yes. It can be re-opened later, if problems are found later.
