### ISSUE TITLE
progress on `adjoining-command` and general commentary of adding custom commands

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [okamsn/loopy#50]
I was working on the `adjoining` command mentioned in #48. And I wanted to relay my thoughts on the experience.

1. distinguishing optional values

I'm having trouble distinguishing between the following cases.

(adjoining var val)
(adjoining var val testfn)
(adjoining val)
(adjoining val testfn)

Maybe the solution to this is to require the keyword `:test` when using `testfn` so there is no ambiguity.

On a side note: better logic pattern matching is needed in emacs lisp. I probably need to talk to emacs devel about this. Specifically pcase needs to be more powerful. I'd like to have something like `(adjoining ,(and (pred symbolp) ,var) ,var ,(optional testfn)))`. Or even something like `(integer-sum ,(one-or-more (pred (integerp))))`. There should be similar keywords to what `rx` has.

2. Adding a new accumulation keyword in a _thorough_ way can be very involved. I'll likely add more examples to adding custom commands in a PR.

I haven't added destructuring for this command yet. Not sure if I need to?

```elisp
(cl-defun loopy%adjoining-command-parser (arg)
  "Add ELT to VAR is ELT is not already in VAR."
  (let (val var)
    (cond ((= 2 (length (cdr arg)))
	   (setq var (cl-second arg))
	   (setq val (cl-third arg))
	   `((loopy--accumulation-vars . (,var ,nil))
	     (loopy--implicit-return . ,var)
	     (loopy--main-body . (setq ,var (cl-adjoin ,val ,var :test #'eql)))
	     (loopy--implicit-return . (setq ,var (nreverse ,var)))))
	  ((and (= 1 (length (cdr arg))) loopy--split-implied-accumulation-results)
	   (setq var (gensym "adjoining-list-"))
	   (setq val (cl-second arg))
	   `((loopy--main-body . (setq ,var (cl-adjoin ,val ,var :test #'eql)))
	     (loopy--implicit-return . (nreverse ,var))))
	  ((= 1 (length (cdr arg)))
	   (setq var (gensym "adjoining-list-"))
	   (setq val (cl-second arg))
	   `((loopy--main-body . (setq ,var (cl-adjoin ,val ,var)))
	     (loopy--implicit-accumulation-final-update . (setq ,var (nreverse ,var)))
	     (loopy--implicit-return . ,var)))
	  (t (error "invalid args: %S" arg)))))

(add-to-list 'loopy-custom-command-parsers '(adjoining . loopy%adjoining-command-parser))
```

**Comment by okamsn** [comment]
> I haven't added destructuring for this command yet. Not sure if I need to?

Ideally, you shouldn't need to. There should probably be a user option for custom accumulation commands, since they need to be handled specially.

I'm making small improvements to how destructuring is handled on the `iter` branch, since the changes build upon the de-duplication effort. Done right, the destructuring systems will eventually recurse down to `(my-adjoin-cmd destructured-var destructured-value)` and will be able to use the instructions for working with single values.

**Comment by okamsn** [comment]
> 1. distinguishing optional values
> 
> I'm having trouble distinguishing between the following cases.
> 
> (adjoining var val)
> (adjoining var val testfn)
> (adjoining val)
> (adjoining val testfn)
> 
> Maybe the solution to this is to require the keyword `:test` when using `testfn` so there is no ambiguity

The simplest way is probably to use `&rest` and `plist-get`. My understanding is that optional values must be given before keyword values in `cl-defun` argument lists. Looking for `:test` in the list of arguments manually would allow you to use a variable number of arguments before the quasi-keyword `:test`.
