### ISSUE TITLE
idea: allowing accumulators to take more than one argument

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [okamsn/loopy#51]
Sometimes I end up using multiple collects. Would be nice to use one.

```elisp
(defun use-package-handler/:silence (name _ fns rest state)
  "Generate forms that silence output of FNS.
FNS is a list of function symbols."
  `(,@(loopy (list fn fns)
	     (collect (use-package%autoload fn name))
	     (collect `(xl-silence-output #',fn)))
    ,@(use-package-process-keywords name rest state)))
```

One collect.

```elisp
(defun use-package-handler/:silence (name _ fns rest state)
  "Generate forms that silence output of FNS.
FNS is a list of function symbols."
  `(,@(loopy (list fn fns)
	     (collect (use-package%autoload fn name) `(xl-silence-output #',fn)))
    ,@(use-package-process-keywords name rest state)))
```

**Comment by okamsn** [comment]
I don't think there is a good way to distinguish between the first argument as an expression and the first argument as a destructured assignment. They both look like a list to the macro.

**Comment by Luis-Henriquez-Perez** [comment]
O.K. I was confused because I didn't understand how accumulators would use destructuring.

```elisp
;; => ((1 2) (3 4))
(loopy (list i '((1 . 3) (2 . 4)))
       (collect (keys . values) i))
```
Certainly, this is very convenient when you want to split an alist or some other data structure by its components as in this example. This is good `flag` potential here. I can see some people preferring this over multiple arguments, but I can so see some would value the convenience of accumulating multiple values more than this. Very low priority though. As (I don't think) we have many users (though I did [advertise loopy slightly on emacs stackexchange](https://emacs.stackexchange.com/questions/63702/equivalent-of-continue-in-cl-loop)). `iter` and reddit posting should come first IMO.

**Comment by okamsn** [comment]
After reflection, I think that a flag would complicate the code for only a small benefit. As you've noted, there is already a way to collect multiple values. There isn't as easy a way to use destructuring with accumulations without using another command, such as `expr`.

So, I think that it is more straightforward to require using multiple commands for multiple accumulations and to allow a single command for a single destructuring.
