### ISSUE TITLE
question: concerning tests

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [okamsn/loopy#52]
In the tests I see you do `(eval (quote ...))`. Why is this instead of simply the loopy form itself?

```elisp
(ert-deftest wrap-pcase-let ()
  (should
   (equal '(1 2 3 4 5 6)
          (eval (quote (loopy-iter (for list i '((1 2) (3 4) (5 6)))
                                   (pcase-let ((`(,a ,b) i))
                                     (accum collect a)
                                     (accum collect b))))))))
```

**Comment by okamsn** [comment]
I started doing this in 132299d7f58954589d2b7b6cb2bda5265f83277b.

It's to make sure that the macro is expanded when the test is run, instead of when the test is defined.

**Comment by Luis-Henriquez-Perez** [comment]
> It's to make sure that the macro is expanded when the test is run, instead of when the test is defined.

Ok. Nice catch. Syntax is awkward and a bit repetitive though, can't we put it in a "test helper" macro or something?

**Comment by okamsn** [comment]
The situation improved a lot with #144, so I consider this goal achieved.
