### ISSUE TITLE
incomplete thoughts and questions about instructions

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [okamsn/loopy#67]
I've been thinking about how to implement certain commands. Particularly `recur` #34 and a "flat" iteration command #27. I will need to somehow know the contents of the loopy body.  I am wondering if there is a way to have stateful interactions between loopy commands. More specifically, I am wondering whether it is possible to view the existing values of instruction variables such as `loopy--main-body`.

I need to think about this and look more into the source code to make more informed comments and possibly take action on how to go about getting this information. Vaguely, I am thinking of `use-package` and how it has implemented its keywords to generate a forms. It's not too different from what loopy does except it uses clauses.

**Comment by okamsn** [comment]
> I've been thinking about how to implement certain commands. Particularly `recur` #34 and a "flat" iteration command #27. I will need to somehow know the contents of the loopy body. I am wondering if there is a way to have stateful interactions between loopy commands. More specifically, I am wondering whether it is possible to view the existing values of instruction variables such as `loopy--main-body`.

For commands which wrap other commands (`if`, `cond`, etc.), it is straightforward to get the list of instructions all of the wrapped commands produced. This can be done using the functions `loopy--parse-loop-commands` and `loopy--extract-main-body`.

In the end, the loop's main body is only finalized after all of the loop commands have been processed. It is easy to wrap commands, but a command does not know that it is being wrapped. The information only flows in one direction. Is this what you are asking about?

**Comment by Luis-Henriquez-Perez** [comment]
> Is this what you are asking about?

I am not sure. I am likely not informed enough. I'll try to implement these commands and I'll keep you posted if I have concrete questions.
