### ISSUE TITLE
Add to Melpa.

### ISSUE THREAD

**Issue by okamsn** [okamsn/loopy#72]
New PR to add to Melpa at: https://github.com/melpa/melpa/pull/7574.

**Comment by tumashu** [comment]
I think this tool should to GNU elpa or emacs.git.

**Comment by okamsn** [comment]
> I think this tool should to GNU elpa or emacs.git.

I would like to add it it ELPA after things are more settled. I have opened #74 to keep track of the things to be done before then.

Now that this package is on MELPA, I am closing this issue.

**Comment by okamsn** [comment]
It is now also on Non-GNU ELPA.
